/**
 * Slack Integration Tools
 * Send notifications, summaries, and alerts
 */

import { FastMCP } from "../../FastMCP.js";

export interface SlackConfig {
  botToken: string;
  channelId: string;
  userId?: string; // For direct messages
}

export interface PARAStatusSummary {
  itemsMoved: {
    count: number;
    fromStage: string;
    toStage: string;
  }[];
  strategicOpportunities: {
    type: string;
    title: string;
    description: string;
    affectedItems: number;
  }[];
  delegationTasks: {
    title: string;
    reason: string;
    estimatedEffort: string;
  }[];
  coherenceIssues: {
    type: string;
    count: number;
    severity: 'low' | 'medium' | 'high';
  }[];
}

export class SlackTools {
  private config: SlackConfig;

  constructor(config: SlackConfig) {
    this.config = config;
  }

  /**
   * Send a formatted summary message to Slack
   */
  async sendSummary(summary: PARAStatusSummary): Promise<void> {
    const message = this.formatSummaryMessage(summary);
    await this.sendMessage(message);
  }

  /**
   * Send a notification about a specific event
   */
  async sendNotification(
    type: 'item_moved' | 'opportunity_found' | 'coherence_issue' | 'delegation_ready',
    details: any
  ): Promise<void> {
    const message = this.formatNotificationMessage(type, details);
    await this.sendMessage(message);
  }

  /**
   * Send a direct message to the user
   */
  async sendDirectMessage(message: string): Promise<void> {
    if (!this.config.userId) {
      throw new Error('User ID not configured for direct messages');
    }

    // Mock implementation - would use Slack API
    console.log(`Sending DM to user ${this.config.userId}: ${message}`);
  }

  /**
   * Send a message to the configured channel
   */
  private async sendMessage(message: string): Promise<void> {
    // Mock implementation - would use Slack API
    console.log(`Sending message to channel ${this.config.channelId}:`);
    console.log(message);
  }

  private formatSummaryMessage(summary: PARAStatusSummary): string {
    let message = "🤖 *PARA Automation Agent - Daily Summary*\n\n";

    // Items moved
    if (summary.itemsMoved.length > 0) {
      message += "📦 *Items Moved Through Funnel:*\n";
      summary.itemsMoved.forEach(move => {
        message += `• ${move.count} items from ${move.fromStage} → ${move.toStage}\n`;
      });
      message += "\n";
    }

    // Strategic opportunities
    if (summary.strategicOpportunities.length > 0) {
      message += "🎯 *Strategic Opportunities Identified:*\n";
      summary.strategicOpportunities.forEach(opp => {
        message += `• *${opp.title}* (${opp.type})\n`;
        message += `  ${opp.description}\n`;
        message += `  Affects ${opp.affectedItems} items\n`;
      });
      message += "\n";
    }

    // Delegation tasks
    if (summary.delegationTasks.length > 0) {
      message += "👥 *Tasks Ready for Delegation:*\n";
      summary.delegationTasks.forEach(task => {
        message += `• *${task.title}*\n`;
        message += `  ${task.reason} (${task.estimatedEffort})\n`;
      });
      message += "\n";
    }

    // Coherence issues
    if (summary.coherenceIssues.length > 0) {
      message += "🔧 *Database Coherence Issues Fixed:*\n";
      summary.coherenceIssues.forEach(issue => {
        const severityEmoji = issue.severity === 'high' ? '🔴' :
                             issue.severity === 'medium' ? '🟡' : '🟢';
        message += `${severityEmoji} ${issue.count} ${issue.type} issues\n`;
      });
      message += "\n";
    }

    message += "_Generated by PARA Automation Agent_";

    return message;
  }

  private formatNotificationMessage(type: string, details: any): string {
    switch (type) {
      case 'item_moved':
        return `📦 Item moved: "${details.title}" from ${details.fromStage} to ${details.toStage}`;

      case 'opportunity_found':
        return `🎯 Strategic opportunity: ${details.title} - ${details.description}`;

      case 'coherence_issue':
        return `🔧 Coherence issue fixed: ${details.type} - ${details.description}`;

      case 'delegation_ready':
        return `👥 Task ready for delegation: ${details.title} (${details.estimatedEffort})`;

      default:
        return `📢 PARA notification: ${JSON.stringify(details)}`;
    }
  }
}

/**
 * Register Slack tools with FastMCP server
 */
export function registerSlackTools(server: FastMCP, slackTools: SlackTools) {
  server.addTool({
    name: "send_para_summary",
    description: "Send a comprehensive PARA status summary to Slack",
    parameters: {
      type: "object",
      properties: {
        summary: {
          type: "object",
          description: "PARA status summary data",
          properties: {
            itemsMoved: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  count: { type: "number" },
                  fromStage: { type: "string" },
                  toStage: { type: "string" }
                }
              }
            },
            strategicOpportunities: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  type: { type: "string" },
                  title: { type: "string" },
                  description: { type: "string" },
                  affectedItems: { type: "number" }
                }
              }
            },
            delegationTasks: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  title: { type: "string" },
                  reason: { type: "string" },
                  estimatedEffort: { type: "string" }
                }
              }
            },
            coherenceIssues: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  type: { type: "string" },
                  count: { type: "number" },
                  severity: { type: "string", enum: ["low", "medium", "high"] }
                }
              }
            }
          }
        }
      },
      required: ["summary"]
    },
    execute: async ({ summary }: { summary: PARAStatusSummary }) => {
      try {
        await slackTools.sendSummary(summary);
        return {
          success: true,
          message: "PARA summary sent to Slack",
          summary
        };
      } catch (error) {
        return { error: `Failed to send summary: ${error.message}` };
      }
    }
  });

  server.addTool({
    name: "send_para_notification",
    description: "Send a specific PARA notification to Slack",
    parameters: {
      type: "object",
      properties: {
        type: {
          type: "string",
          enum: ["item_moved", "opportunity_found", "coherence_issue", "delegation_ready"],
          description: "Type of notification"
        },
        details: {
          type: "object",
          description: "Notification details",
          properties: {
            title: { type: "string" },
            description: { type: "string" },
            fromStage: { type: "string" },
            toStage: { type: "string" },
            estimatedEffort: { type: "string" }
          }
        }
      },
      required: ["type", "details"]
    },
    execute: async ({ type, details }: { type: string; details: any }) => {
      try {
        await slackTools.sendNotification(type as any, details);
        return {
          success: true,
          message: `PARA notification sent: ${type}`,
          type,
          details
        };
      } catch (error) {
        return { error: `Failed to send notification: ${error.message}` };
      }
    }
  });

  server.addTool({
    name: "send_direct_message",
    description: "Send a direct message to the PARA agent user",
    parameters: {
      type: "object",
      properties: {
        message: {
          type: "string",
          description: "Message content to send"
        }
      },
      required: ["message"]
    },
    execute: async ({ message }: { message: string }) => {
      try {
        await slackTools.sendDirectMessage(message);
        return {
          success: true,
          message: "Direct message sent",
          content: message
        };
      } catch (error) {
        return { error: `Failed to send direct message: ${error.message}` };
      }
    }
  });
}

